name: Documentation Regulator
on:
  push:
    paths:
      - '**.md'
      - '!docs/**'
    branches-ignore:
      - 'dev'
      - 'main'
jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.actor != 'github-actions[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Update docs structure
        run: python .github/scripts/update_docs.py --exclude-dirs assets

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Update documentation structure'
          git push
